# Generated by Django 4.2.6 on 2023-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_employee_id_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
